version: "3"
services: 
  react-app:
      image: react-app
      stdin_open: true
      ports: 
        - "3000:3000"
      networks:
        - full-app
  node-app:
   # container_name: node-app
    image: node-app
    restart: always
    build: .
    ports:
      - 4050:4000 
    networks:
      - full-app
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  C:\\\:/var/lib/mysql
  networks:
    full-app:
        driver: bridge
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: rest
      MYSQL_ROOT_PASSWORD: secret